# Project Euler Problem 2
# Even Fibonacci Numbers
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
def comp():
    ans = 0
    n1, n2 = 1, 2
    while n1 < 4000000:
        if n1 % 2 == 0:
            ans += n1
        n1, n2 = n2, n1 + n2
    return str(ans)
    
if __name__ == '__main__':
    print(comp())
